language: python

os: linux

dist: xenial

python:
  - '3.5.2'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'pypy3.5'

install:
  - pip install tox-travis codecov

script: tox

after_success: |
  VERSION="python_${TRAVIS_PYTHON_VERSION//[^[:alnum:]]/}" &&
  codecov --required --flags $VERSION ||
  (sleep 5 && codecov --required --flags $VERSION) ||
  (sleep 10 && codecov --required --flags $VERSION) ||
  (sleep 20 && codecov --required --flags $VERSION) ||
  (sleep 30 && codecov --required --flags $VERSION)
